apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      secretKeyRef:
        name: redis:password
        key: redis:password
    - name: actorStateStore
      value: 'false'
    - name: keyPrefix
      value: 'cart'
    - name: enableTLS
      value: 'false'
auth:
  secretStore: secretstore
